apiVersion: v1
kind: Namespace
metadata:
  name: gallery
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gallery-env
  namespace: gallery
data:
  # ENV untuk aplikasi
  FLASK_SECRET_KEY: "please-change-me"
  # Lokasi file config di dalam container (dipasang dari Secret via volume)
  CONFIG_PATH: "/app/config.ini"
---
apiVersion: v1
kind: Secret
metadata:
  name: gallery-config
  namespace: gallery
type: Opaque
stringData:
  # Isi file config.ini kamu. Edit sesuai MinIO-mu.
  # Secret ini akan dimount sebagai /app/config.ini
  config.ini: |
    [MINIO]
    ENDPOINT = 172.31.64.1:9000
    ACCESS_KEY = DQ161SYuCgpFufVDFOTa
    SECRET_KEY = Hf2CC3XL1LFqa7QW1Vm1U8svkEDq957KmEJKcdp7
    BUCKET = gallery
    SECURE = false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-minio-gallery
  namespace: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-minio-gallery
  template:
    metadata:
      labels:
        app: flask-minio-gallery
    spec:
      containers:
        - name: web
          image: lethisaputri/flask-minio-gallery:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: gallery-env
          volumeMounts:
            - name: config-file
              mountPath: /app/config.ini
              subPath: config.ini
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config-file
          secret:
            secretName: gallery-config
            items:
              - key: config.ini
                path: config.ini
---
apiVersion: v1
kind: Service
metadata:
  name: flask-minio-gallery
  namespace: gallery
spec:
  type: ClusterIP
  selector:
    app: flask-minio-gallery
  ports:
    - name: http
      port: 5000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-minio-gallery
  namespace: gallery
spec:
  ingressClassName: nginx
  rules:
    - host: gallery.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-minio-gallery
                port:
                  number: 5000
